# Generated by Django 4.1.2 on 2022-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale2',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
