# Generated by Django 4.1.1 on 2022-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=255)),
                ('ventas', models.IntegerField()),
                ('pred_value', models.IntegerField()),
                ('real_value', models.IntegerField()),
            ],
        ),
    ]
