# Generated by Django 4.1.2 on 2023-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='mes',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='pred_value',
            new_name='prediction',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='real_value',
            new_name='real_values',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='ventas',
            new_name='sales',
        ),
        migrations.AddField(
            model_name='demand',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
