# Generated by Django 4.1.2 on 2022-12-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='totalPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='sale',
            name='totalDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
